# This is a basic workflow that is manually triggered

name: Trigger Pester Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'branch name to checkout'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger_pester:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo ${{ github.event.inputs.name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.name }}

      - name: Invoke Pester Tests
        run: |
          cd Tests
          Install-Module -Name psyml -force
          Invoke-Pester YamlSyntax.Tests.ps1 -output detailed
        shell: pwsh

      - name: Make my day sunny
        run: echo "Bruce Springsteen - Waitin' On A Sunny Day https://www.youtube.com/watch?v=TiCxqhu9cio"