# This is a basic workflow that is manually triggered

name: Trigger Pester Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'branch name to checkout'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger_pester:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo ${{ github.event.inputs.name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.name }}

      - name: Check out feature branch
        run: |
          git checkout -b $branch_name
          git config --global user.email "it@martin-walther.ch"
          git config --global user.name "Martin Walther"
          cd Tests
          Invoke-Pester YamlSyntax.Tests.ps1 -output detailed
        shell: pwsh
  # This workflow contains a single job called "greet"
  # greet:
    # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
    # Runs a single command using the runners shell
  #   - name: Send greeting
  #     run: echo "Hello ${{ github.event.inputs.name }}"
