name: New computer -> checkout feature branch and create computer

on:
  issues:
    types:
      - opened

jobs:
  new-computer-request:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: pwsh

    steps:
      - name: Set variable
        id: set-var
        run : |
          $feature_branch = $(( "${{ github.event.issue.title }}" ).ToLower()) -replace '\s', ''
          echo "::set-output name=feature_branch::$feature_branch"
          Write-Host $feature_branch

      - name: Clone repo ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check out feature branch
        run: |
          Write-Host "Issue ${{ steps.set-var.outputs.feature_branch }} created on ${{ github.repository }}"
          git checkout -b ${{ steps.set-var.outputs.feature_branch }}
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add new file to feature branch
        run: |
          $body_content = $( "${{ github.event.issue.body }}" ) -replace "`r`n", ' '
          if([String]::IsNullOrEmpty($body_content)){
            $CommitMessage = ./Bin/New-BranchContent.ps1 -BranchName ${{ steps.set-var.outputs.feature_branch }} -verbose
          }else{
            $CommitMessage = ./Bin/New-BranchContent.ps1 -BranchName ${{ steps.set-var.outputs.feature_branch }} -BodyContent $body_content -verbose
          }
          git add .
          git commit -m $CommitMessage

      - name: Push feature branch
        run: |
          git push origin ${{ steps.set-var.outputs.feature_branch }}

      - name: Close Issue ${{ github.event.issue.number }} ${{ steps.set-var.outputs.feature_branch }}
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue, branch ${{ steps.set-var.outputs.feature_branch }} created successfully
