# This is a basic workflow to help you get started with Actions
name: New issue -> checkout feature branch

# Controls when the workflow will run
on:
  # Triggers the workflow on issue request events
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new_issue:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: pwsh
    env:
        BRANCH_NAME: $( "${{ github.event.issue.title }}" ) -replace '\s', '_'

    steps:
      - name: Echo Branch name
        run: Write-Host "Issue ${{ env.BRANCH_NAME }}"

      - name: Clone repo ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check out feature branch for issue ${{ github.event.issue.title }}
        run: |
          $branch_name = $( "${{ github.event.issue.title }}" ) -replace '\s', '_'
          Write-Host "Issue ${{ github.event.issue.title }} created on ${{ github.repository }}"
          git checkout -b $branch_name
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add new file to feature branch
        run: |
          $branch_name   = $( "${{ github.event.issue.title }}" ) -replace '\s', '_'
          $body_content  = $( "${{ github.event.issue.body }}" ) -replace "`r`n", ' '
          $CommitMessage = ./Bin/New-BranchContent.ps1 -BranchName $branch_name -BodyContent $body_content -verbose
          git add .
          git commit -m $CommitMessage

      - name: Push feature branch
        run: |
          $branch_name = $( "${{ github.event.issue.title }}" ) -replace '\s', '_'
          git push origin $branch_name

      - name: Close Issue ${{ github.event.issue.number }} ${{ github.event.issue.title }}
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue, branch ${{ github.event.issue.title }} created successfully
