name: New issue -> checkout feature branch

on:
  issues:
    types:
      - opened

jobs:
  new_issue:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: pwsh

    steps:
      - name: Clone repo ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check out feature branch
        run: |
          Write-Host "Issue ${{ github.event.issue.title }} created on ${{ github.repository }}"
          git checkout -b ${{ github.event.issue.title }}
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add new file to feature branch
        run: |
          $body_content  = $( "${{ github.event.issue.body }}" ) -replace "`r`n", ' '
          $CommitMessage = ./Bin/New-BranchContent.ps1 -BranchName ${{ github.event.issue.title }} -BodyContent $body_content -verbose
          git add .
          git commit -m $CommitMessage

      - name: Push feature branch
        run: |
          git push origin ${{ github.event.issue.title }}

      - name: Close Issue ${{ github.event.issue.number }} ${{ github.event.issue.title }}
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue, branch ${{ github.event.issue.title }} created successfully
