# This is a basic workflow to help you get started with Actions

name: New issue

# Controls when the workflow will run
on:
  # Triggers the workflow on issue request events
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Check out feature branch
        run: |
          echo "Issue created: ${{ github.event.issue.title }}, on ${{ github.repository }}"
          git checkout -b feature_branch
          git push origin feature_branch