# This is a basic workflow to help you get started with Actions

name: New issue

# Controls when the workflow will run
on:
  # Triggers the workflow on issue request events
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Check out feature branch
        run: |
          $branch_name = $(${{ github.event.issue.title }} -replace '\s', '_').Substring(0,10)
          echo "Issue ${{ github.event.issue.title }} created on ${{ github.repository }}"
          git checkout -b $branch_name
          git push origin $branch_name
        shell: pwsh