# This is a basic workflow to help you get started with Actions

name: New issue

# Controls when the workflow will run
on:
  # Triggers the workflow on issue request events
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new_issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: main

    # Runs a single command using the runners shell
    - name: Send notification
      run: | 
        echo "New issue opend on ${{ github.repository }}"
        echo "Issue created: ${{ github.event.issue.title }}"

    - name: Check out feature branch
      run: |
        git checkout -b feature_branch
        git push origin feature_branch