# This is a basic workflow to help you get started with Actions

name: New issue

# Controls when the workflow will run
on:
  # Triggers the workflow on issue request events
  issues:
    types:
      - opened

jobs:
  New issue:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "New issue opend on ${{ github.repository }}"