# This is a basic workflow to help you get started with Actions
name: New issue

# Controls when the workflow will run
on:
  # Triggers the workflow on issue request events
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check out feature branch
        run: |
          $branch_name = $( "${{ github.event.issue.title }}" ) -replace '\s', '_'
          Write-Host "Issue ${{ github.event.issue.title }} created on ${{ github.repository }}"
          Write-Host "Body:"
          Write-Host "${{ github.event.issue.body }}"
          git checkout -b $branch_name
          git config --global user.email "it@martin-walther.ch"
          git config --global user.name "Martin Walther"
          cd Nodes
          $ExampleYaml = "$($branch_name).yml"
          Add-Content -Path $ExampleYaml "- Name: $($branch_name)"
          Add-Content -Path $ExampleYaml "  IPAddress: 192.168.254.10"
          Add-Content -Path $ExampleYaml "  Subnet: 255.255.255.0"
          Add-Content -Path $ExampleYaml "  Gateway: 192.168.254.1"
          Add-Content -Path $ExampleYaml "  Status: new"
          Add-Content -Path $ExampleYaml "${{ github.event.issue.body }}"
          git add .
          git commit -m "Add $ExampleYaml"
          git push origin $branch_name
        shell: pwsh

      - name: Close Issue ${{ github.event.issue.number }} ${{ github.event.issue.title }}
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue, branch ${{ github.event.issue.title }} created successfully
