name: Upload artifact from Ubuntu

# Controls when the workflow will run
on: [push]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger_pester:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        
    steps:
      - name: Test with Pester
        uses: actions/checkout@v3
        run: |
          cd Tests
          Install-Module -Name psyml -force
          Import-Module -Name Pester -MinimumVersion 5.3.3
          $config = [PesterConfiguration]::Default
          $config.Filter.Tag = "Required"
          $config.Output.Verbosity = 'Detailed'
          $config.Run.PassThru = $true
          Invoke-Pester -Configuration $config | Export-CliXml -Path Unit.Tests.xml -Force
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-Unit-Tests
          path: Unit.Tests.xml
    if: ${{ always() }}
