name: Add computer -> run Pester Tests, upload results and merge to deploy

on:
  pull_request:
    branches: [main, test, deploy]
    
jobs:
  add-new-computer-to-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        
    steps:
      - name: Clone repo ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout branch
        run: |
          $feature_branch = $("${{ github.event.pull_request.title }}").ToLower()
          git checkout -b $feature_branch
          $currentbranch = git branch --show-current
          Write-Host "Current branch is $currentbranch"

      - name: Invoke Pester Tests
        run: |
          Write-Host "Install and import Modules"
          Install-Module -Name psyml -force
          Import-Module -Name Pester -MinimumVersion 5.3.3

          Write-Host "Initialize path-variable"
          $ParentLocation = Get-Location | Select -ExpandProperty Path
          $ReportsPath    = Join-Path -Path $ParentLocation -ChildPath 'Reports'
          $TestsPath      = Join-Path -Path $ParentLocation -ChildPath 'Tests'
          $BinPath        = Join-Path -Path $ParentLocation -ChildPath 'Bin'
          $ReadmeFullName = Join-Path -Path $ParentLocation -ChildPath 'README.md'
          $ReportFullName = Join-Path -Path $ReportsPath -ChildPath 'Last-TestsReport.NUnitXml'
          $CsvFullName    = $($ReportFullName -replace '.NUnitXml', '.csv')

          Write-Host "Run Pester Tests"
          $config = [PesterConfiguration]::Default
          $config.Run.Path           = $TestsPath
          $config.Filter.Tag         = "Required"
          $config.Output.Verbosity   = 'Normal'
          $config.Run.PassThru       = $true
          $config.Run.Throw          = $true
          $NUnitReport = Invoke-Pester -Configuration $config

          Write-Host "Create Last-TestsReport.NUnitXml"
          if(-not(Test-Path $ReportsPath)){
            $null = New-Item -Path $ReportsPath -ItemType Directory
          }
          $NUnitReport | Export-NUnitReport -Path $ReportFullName #Last-TestsReport.NUnitXml
          
          Write-Host "Create CSV-Report"
          if(Test-Path $CsvFullName){
            $null = Remove-Item -Path $CsvFullName -Force
          }
          $result = . "$($BinPath)/Read-FromXML.ps1" -Inputfile $ReportFullName
          $result.Tests | ConvertTo-Csv | Out-File -FilePath $($ReportFullName -replace '.NUnitXml', '.csv') -Encoding utf8 -NoClobber -Force

          Write-Host "Update README.md"
          Add-Content -Path $ReadmeFullName -Value "$($result.ExecutedAt)|$($result.Result)|$($result.TotalCount)|$($result.PassedCount)|$($result.FailedCount)|$($result.ErrorCount)|$($result.SkippedCount)|$($result.NotRunCount)"

      - name: Upload changes
        if: ${{ always() }}
        run: |
          Write-Host "Upload results"
          git config user.name github-actions
          git config user.email github-actions@github.com
          $currentbranch = git branch --show-current
          Write-Host "Current branch is $currentbranch"
          $CommitMessage = "Upload Last-TestsReport"
          git add .
          git commit -m $CommitMessage
          git push origin $currentbranch

      - name: Merge ${{ github.event.pull_request.title }} to deploy
        if: ${{ success() }}
        run: |
          $feature_branch = $("${{ github.event.pull_request.title }}").ToLower()
          git fetch --unshallow
          git checkout -b deploy
          git pull
          git merge --no-ff $feature_branch -m "Auto-merge $feature_branch to deploy"
          git push

      - name: Delete feature branch
        if: ${{ success() }}
        run: |
          $feature_branch = $("${{ github.event.pull_request.title }}").ToLower()
          if(($feature_branch -notmatch 'main') -or ($feature_branch -notmatch 'test')){
            git push --delete origin $feature_branch
          }else{
            Write-Host "$feature_branch is excluded from Autodelete"
          }
