# This is a basic workflow to help you get started with Actions

name: Pull request -> run Pester Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger_pester:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        
    steps:
      # Clone repo
      - name: Clone repo ${{ github.event.pull_request.head.sha }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Do magic things and commit
      - name: Do Magic things
        run: Write-Host "Autocommit ${{ github.event.pull_request.head }}"

      # Push feature branch
      - name: Push feature branch
        run: Write-Host "Autopush ${{ github.event.pull_request.head }}"

      # Run Pester Tests
      - name: Invoke Pester Tests
        run: |
          cd Tests
          Install-Module -Name psyml -force
          Import-Module -Name Pester -MinimumVersion 5.3.3
          $config = [PesterConfiguration]::Default
          $config.Filter.Tag = "Required"
          $config.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $config

      # Merge in to main branch
      - name: Merge in to main branch
        run: Write-Host "Automerge  ${{ github.event.pull_request.head }}"

      # Delete feature branch
      - name: Delete feature branch
        run: Write-Host "Autodelete ${{ github.event.pull_request.head }}"
