name: Trigger Pester Tests -> run Pester Tests and upload results

# Controls when the workflow will run
on: 
#  push:
#    branches-ignore:
#    - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'branch name to checkout'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger_pester:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        
    steps:
      - name: Clone repo ${{ github.event.inputs.name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.name }}

      - name: Test with Pester
        run: |
          Write-Host "Install and import Modules"
          $ParentLocation = Get-Location | Select -ExpandProperty Path
          Install-Module -Name psyml, pshtml -force
          Import-Module -Name Pester -MinimumVersion 5.3.3
          
          Write-Host "Run Pester Tests"
          cd Tests
          $config = [PesterConfiguration]::Default
          $config.Filter.Tag = "Required"
          $config.Output.Verbosity = 'Detailed'
          $config.Run.PassThru = $true
          $NUnitReport = Invoke-Pester -Configuration $config

          Write-Host "Create Last-TestsReport.NUnitXml"
          $ReportsPath = Join-Path -Path $ParentLocation -ChildPath 'Reports'
          if(-not(Test-Path $ReportsPath)){
            $null = New-Item -Path $ReportsPath -ItemType Directory
          }
          cd $ReportsPath
          $NUnitReport | Export-NUnitReport -Path Last-TestsReport.NUnitXml
          
          Write-Host "Create CSV-Report"
          $BinPath = Join-Path -Path $ParentLocation -ChildPath 'Bin'
          cd $BinPath
          $result = ./Read-FromXML.ps1 -Inputfile $(Join-Path -Path $(ReportsPath -ChildPath 'Last-TestsReport.NUnitXml') -Verbose
          $result.Tests | ConvertTo-Csv | Out-File -FilePath $(ReportsPath -ChildPath 'Last-TestsReport.csv') -Encoding utf8 -NoClobber

      - name: Upload Pester Result
        run: |
          git config --global user.email "it@martin-walther.ch"
          git config --global user.name "Martin Walther"
          git add .
          git commit -m "Upload Last-TestsReport.NUnitXml"
          git push

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      #if: ${{ always() }}

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
